service: truenorth-calculator-api

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 30

plugins:
- serverless-offline

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  api:
    handler: dist/app.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}