service: truenorth-calculator-api

provider:
  name: aws
  runtime: nodejs16.x
  timeout: 30

  environment:
    NODE_ENV: ${opt:stage, 'development'}

custom:
  serverless-offline:
    host: 0.0.0.0

functions:
  api:
    handler: dist/app.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-webpack

webpack:
  webpackConfig: webpack.config.js